export const LOGIN_ANIMATION_WORDS = [
  "Instagram TikTok Twitter",
  "Slow Wi-Fi or Low Battery",
  "What’s Your Strategy",
  "Batman or Iron Man",
  "Pizza & Pineapple",
  "iPhone or Android",
  "Socialize or Hide",
  "Best Villain Ever",
  "Is it GIF or JIF",
  "Netflix or Apple",
  "Best Pixar Movie",
  "Do Aliens Exist",
  "Road Trip Music",
  "Fries vs. Chips",
  "Which Is Worse",
  "Best Memes",
];

export const RANDOM_COLORS = [
  "#EEC643",
  "#48BEFF",
  "#F56476",
  "#F6E27F",
  "#41D3BD",
  "#EF8A17",
  "#09BC8A",
  "#A997DF",
  "#F56476",
  "#C3BF6D",
  "#59A96A",
  "#F56476",
  "#3B8EA5",
  "#AEFFD8",
  "#788BFF",
  "#EEB902",
  "#97CC04",
];
